### ISSUE TITLE
Float data cannot run

### ISSUE THREAD

**Issue by 312516784** [qiqi12/extreme-clustering#3]
I ran the "flame". "spiral" and "a3", but they couldn't run. So I try to use some other float data, but all of them cannot run.
Ps: 'IsGauss' I selected 'True'

**Comment by qiqi12** [comment]
I have checked that my code is working. What error did you get when you ran the code?

**Comment by haorui-harry** [comment]
i only change the np.loadtxt and set the file to "data-sets/a1.txt",but finally the program told me "IndexError: index 3000 is out of bounds for axis 1 with size 3000"
and i use my dataset and found the same error!
Maybe there is something wrong with the code file named "Extreme_Clustering.py" 
the error is described as"Traceback (most recent call last):
  File "C:\Users\h\PycharmProjects\extreme-clustering\Python version\main.py", line 25, in <module>
    clusteringResult = Extreme_Clustreing(data, 70000, False)
  File "C:\Users\h\PycharmProjects\extreme-clustering\Python version\Extreme_Clustering.py", line 46, in Extreme_Clustreing
    while density[i] >= density[c[i,j]] and b[i,j] < neighbuorhood_radius:
IndexError: index 3000 is out of bounds for axis 1 with size 3000"
wish your help and thank you very much

**Comment by 312516784** [comment]
> I have checked that my code is working. What error did you get when you ran the code?

Thanks for your reply. I have dealt with the problem, and the error is that 'neighbuorhood_radius' number is unreasonable.

**Comment by haorui-harry** [comment]
> 

hello,brother!
i am glad to hear the good news! And now i have trouble in my code !
how do you find the bug

**Comment by qiqi12** [comment]
> > 
> 
> hello,brother! i am glad to hear the good news! And now i have trouble in my code ! how do you find the bug

You should adjust 'neighbuorhood_radius'

**Comment by qiqi12** [comment]
> You should adjust 'neighbuorhood_radius'

**Comment by qiqi12** [comment]
> i only change the np.loadtxt and set the file to "data-sets/a1.txt",but finally the program told me "IndexError: index 3000 is out of bounds for axis 1 with size 3000" and i use my dataset and found the same error! Maybe there is something wrong with the code file named "Extreme_Clustering.py" the error is described as"Traceback (most recent call last): File "C:\Users\h\PycharmProjects\extreme-clustering\Python version\main.py", line 25, in clusteringResult = Extreme_Clustreing(data, 70000, False) File "C:\Users\h\PycharmProjects\extreme-clustering\Python version\Extreme_Clustering.py", line 46, in Extreme_Clustreing while density[i] >= density[c[i,j]] and b[i,j] < neighbuorhood_radius: IndexError: index 3000 is out of bounds for axis 1 with size 3000" wish your help and thank you very much

You should adjust 'neighbuorhood_radius'

**Comment by haorui-harry** [comment]
> 
thanks for your help
I am surprised because of your smart idea in your paper!
But how to adjust neighbor-radius effectively and I use your program to analyze a dataset 
And get a picture like this 
![E99E455C-405E-4F48-8E66-D94CF34E61A3](https://user-images.githubusercontent.com/111951108/196325870-a9c9fbbe-6d4e-4ffb-8d10-0250a597ec90.png)
You can see the points around are classified into so many kinds ,so the num of kinds can not be determined !
Can peak cluster make sense?
is there something wrong with my neighbor-radius or maybe you can do something to make your idea better!

**Comment by qiqi12** [comment]
> > 
> 
> thanks for your help I am surprised because of your smart idea in your paper! But how to adjust neighbor-radius effectively and I use your program to analyze a dataset And get a picture like this ![E99E455C-405E-4F48-8E66-D94CF34E61A3](https://user-images.githubusercontent.com/111951108/196325870-a9c9fbbe-6d4e-4ffb-8d10-0250a597ec90.png) You can see the points around are classified into so many kinds ,so the num of kinds can not be determined ! Can peak cluster make sense? is there something wrong with my neighbor-radius or maybe you can do something to make your idea better!

Let d(o_i) be the distance between object o_i and its nearest neighbor, and N is the number of objects in the dataset, then dc=\frac{1}{N}\sum_{i=1}^{N}{d(o_i)}, that is, dc is the mean value of the distance between the object and its nearest neighbor. As a rule of thumb, setting "neighbuorhood_radius" to 5 to 10 times dc produces satisfactory results.
